version: "3.5"

services:
  wiremock:
    build :
      dockerfile:  Dockerfile
      context: ./wiremock
    command: "--verbose"
    image: wiremock/wiremock:latest
    networks:
      - spring-cloud-network
    ports:
      - 8081:8080

  night-time-temperature:
    image: night-time-temperature/get-temp:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=${ENV}"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge